call tns plugin update nativescript-feedback
call tns plugin update nativescript-floatingactionbutton
call tns plugin update nativescript-localize
call tns plugin update nativescript-ngx-fonticon
call tns plugin update nativescript-toast
call tns plugin update nativescript-ui-listview
call tns plugin update nativescript-ui-sidedrawer
call tns plugin update nativescript-ui-dataform
call tns plugin update nativescript-ui-autocomplete